// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"zzw/internal/dao/internal"
)

// internalAddressDao is internal type for wrapping internal DAO implements.
type internalAddressDao = *internal.AddressDao

// addressDao is the data access object for table Address.
// You can define custom methods on it to extend its functionality as you wish.
type addressDao struct {
	internalAddressDao
}

var (
	// Address is globally public accessible object for table Address operations.
	Address = addressDao{
		internal.NewAddressDao(),
	}
)

// Fill with you ideas below.
