// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Address is the golang structure for table Address.
type Address struct {
	Id      int64  `json:"id"      description:"UID"`
	Addr    string `json:"addr"    description:"账户地址"`
	Iswhite int    `json:"iswhite" description:"是否白名单"`
}
